# ============================================================================
# Embedded Nerd - Internal Link Engine V3.6
# ============================================================================
#
# Jekyll 3.10 compatible
#
# Relationship engine:
#   Article -> Product
#   Article -> Article
#   Product -> Article
#   Product -> Product
#
# V3.6 improvements:
#   - Supports internal_links.overrides
#   - Strong natural-anchor validation
#   - Generic keyword protection
#   - Product IDs are fallback anchors, not preferred anchors
#   - Explicit internal_link_keywords remain supported
#   - Automatically derives useful technical product anchors
#   - Better handling of technical product names
#   - Required hardware gets highest relevance
#   - Product -> Article can use required hardware anchors
#   - Product -> Article can use hardware-derived anchors
#   - General index pages are excluded from article graph
#   - Product-to-product remains deliberately conservative
#   - Existing HTML/Markdown links are protected
#   - Protected HTML/code blocks are never modified
#   - Duplicate hook protection
#   - Analysis mode supported
#
# ============================================================================

module EmbeddedNerd

  module InternalLinker

    # ========================================================================
    # DEFAULT SETTINGS
    # ========================================================================

    DEFAULT_SETTINGS = {
      "enabled" => true,
      "analysis_only" => false,
      "max_total_links_per_page" => 8,
      "max_product_links_per_page" => 4,
      "max_article_links_per_page" => 4,
      "minimum_relevance" => 65,
      "analysis_results_per_page" => 5,
      "minimum_confidence" => "medium",
      "high_confidence_score" => 85,
      "medium_confidence_score" => 70
    }.freeze

    # ========================================================================
    # PROTECTED ELEMENTS
    # ========================================================================

    PROTECTED_TAGS = %w[
      a
      h1
      h2
      h3
      h4
      h5
      h6
      code
      pre
      script
      style
      textarea
    ].freeze

    # Words useful for topical scoring but too generic to be used as
    # automatic anchors.
    GENERIC_ANCHORS = %w[
      arduino
      esp32
      esp8266
      raspberry pi
      raspberry-pi
      electronics
      electronic
      device
      devices
      module
      modules
      sensor
      sensors
      display
      displays
      screen
      screens
      board
      boards
      development board
      development boards
      project
      projects
      tutorial
      guide
      code
      example
      examples
      robotics
      prototyping
      component
      components
      hardware
      microcontroller
      microcontrollers
    ].freeze

    AUTO_LINK_ATTRIBUTE =
      'data-embedded-nerd-auto-link="true"'.freeze

    AUTO_LINK_PATTERN =
      /<a\b[^>]*data-embedded-nerd-auto-link=["\']true["\'][^>]*>.*?<\/a>/im

    EDITORIAL_LAYOUTS = %w[
      article
      post
      tutorial
      single
    ].freeze

    # ========================================================================
    # MAIN PROCESSOR
    # ========================================================================

    def self.process(document)

      site =
        document.site

      config =
        site.data["internal_links"]

      return unless config.is_a?(Hash)

      settings =
        DEFAULT_SETTINGS.merge(
          config["settings"] || {}
        )

      return unless settings["enabled"]

      graph =
        build_graph(site)

      return unless graph

      current_url =
        normalize_url(document.url)

      current =
        graph[:by_url][current_url]

      return unless current

      # Remove only links generated by this engine if the hook is invoked
      # more than once during the same build.
      clean_content =
        remove_generated_links(
          document.content.to_s
        )

      document.content =
        clean_content

      current[:content] =
        clean_content

      relations =
        find_relations(
          current,
          graph,
          settings,
          config
        )

      log_analysis(
        current,
        relations,
        settings
      )

      return if settings["analysis_only"]

      new_content =
        insert_links(
          current,
          relations,
          settings
        )

      if new_content != current[:content]

        document.content =
          new_content

        Jekyll.logger.info(
          "Embedded Nerd:",
          "V3.6 inserted #{count_generated_links(new_content)} automatic link(s)"
        )

      end
    end

    # ========================================================================
    # CONTENT GRAPH
    # ========================================================================

    def self.build_graph(site)

      cache_key =
        :@embedded_nerd_internal_graph_v36

      if site.instance_variable_defined?(cache_key)

        return site.instance_variable_get(
          cache_key
        )

      end

      config =
        site.data["internal_links"] || {}

      products = []
      articles = []
      by_url = {}
      by_product_id = {}

      # ----------------------------------------------------------------------
      # Products in site.pages
      # ----------------------------------------------------------------------

      site.pages.each do |page|

        data =
          page.data || {}

        next unless
          data["layout"].to_s == "product"

        product =
          build_product(
            page,
            config
          )

        add_product(
          product,
          products,
          by_url,
          by_product_id
        )

      end

      # ----------------------------------------------------------------------
      # Products in collections
      # ----------------------------------------------------------------------

      site.collections.each do |_label, collection|

        collection.docs.each do |document|

          data =
            document.data || {}

          next unless
            data["layout"].to_s == "product"

          product =
            build_product(
              document,
              config
            )

          add_product(
            product,
            products,
            by_url,
            by_product_id
          )

        end

      end

      # ----------------------------------------------------------------------
      # Posts
      # ----------------------------------------------------------------------

      site.posts.docs.each do |post|

        add_article(
          build_article(post),
          articles,
          by_url
        )

      end

      # ----------------------------------------------------------------------
      # Explicit editorial pages
      # ----------------------------------------------------------------------

      site.pages.each do |page|

        data =
          page.data || {}

        next if
          data["layout"].to_s == "product"

        next if
          excluded_editorial_page?(page)

        next unless
          data["internal_links"] == true

        add_article(
          build_article(page),
          articles,
          by_url
        )

      end

      # ----------------------------------------------------------------------
      # Editorial collections
      # ----------------------------------------------------------------------

      site.collections.each do |label, collection|

        next if
          label.to_s == "posts"

        collection.docs.each do |document|

          data =
            document.data || {}

          next if
            data["layout"].to_s == "product"

          next if
            excluded_editorial_page?(document)

          next unless
            editorial_collection_document?(document)

          add_article(
            build_article(document),
            articles,
            by_url
          )

        end

      end

      graph = {
        products: products,
        articles: articles,
        by_url: by_url,
        by_product_id: by_product_id
      }

      build_product_article_index(
        graph
      )

      site.instance_variable_set(
        cache_key,
        graph
      )

      Jekyll.logger.info(
        "Embedded Nerd:",
        "Content Graph V3.6: #{products.length} products, #{articles.length} articles"
      )

      graph
    end

    # ========================================================================
    # PRODUCT / ARTICLE INDEX
    # ========================================================================

    def self.build_product_article_index(graph)

      graph[:product_articles] =
        Hash.new do |hash, key|

          hash[key] = []

        end

      graph[:articles].each do |article|

        article[:required_hardware].each do |product_id|

          next if
            product_id.empty?

          next unless
            graph[:by_product_id].key?(product_id)

          list =
            graph[:product_articles][product_id]

          list <<
            article[:id] unless
            list.include?(article[:id])

        end

      end

      graph[:articles].each do |article|

        graph[:products].each do |product|

          next if
            graph[:product_articles][product[:id]].include?(
              article[:id]
            )

          next unless
            product_mentioned_in_article?(
              product,
              article
            )

          graph[:product_articles][product[:id]] <<
            article[:id]

        end

      end
    end

    # ========================================================================
    # BUILD PRODUCT
    # ========================================================================

    def self.build_product(
      document,
      config = {}
    )

      data =
        document.data || {}

      product_id =
        data["product_id"].to_s.strip

      title =
        data["title"].to_s.strip

      text = [
        title,
        data["excerpt"],
        data["description"],
        data["manufacturer"],
        Array(data["tags"]).join(" "),
        Array(data["categories"]).join(" ")
      ].compact.join(" ")

      override =
        product_override(
          config,
          product_id
        )

      {
        type: :product,
        id: product_id,
        title: title,
        url: document.url,
        text: normalize_text(text),
        tokens: tokenize(text),
        tags: normalize_array(data["tags"]),
        categories: normalize_array(data["categories"]),
        related: normalize_ids(data["related"]),
        keywords: product_keywords(
          data,
          override
        ),
        content: document.content.to_s
      }
    end

    # ========================================================================
    # BUILD ARTICLE
    # ========================================================================

    def self.build_article(document)

      data =
        document.data || {}

      title =
        data["title"].to_s.strip

      content =
        document.content.to_s

      text = [
        title,
        data["excerpt"],
        data["description"],
        Array(data["tags"]).join(" "),
        Array(data["categories"]).join(" "),
        content
      ].compact.join(" ")

      {
        type: :article,
        id: normalize_url(document.url),
        title: title,
        url: document.url,
        text: normalize_text(text),
        tokens: tokenize(text),
        tags: normalize_array(data["tags"]),
        categories: normalize_array(data["categories"]),
        required_hardware:
          extract_hardware_ids(
            data["required_hardware"]
          ),
        related:
          normalize_ids(
            data["related"]
          ),
        keywords:
          article_keywords(data),
        content: content
      }
    end

    # ========================================================================
    # ADD NODES
    # ========================================================================

    def self.add_product(
      product,
      products,
      by_url,
      by_product_id
    )

      return if
        product[:id].empty?

      return if
        by_product_id.key?(product[:id])

      normalized_url =
        normalize_url(
          product[:url]
        )

      return if
        by_url.key?(normalized_url)

      products <<
        product

      by_url[normalized_url] =
        product

      by_product_id[product[:id]] =
        product
    end

    def self.add_article(
      article,
      articles,
      by_url
    )

      url =
        normalize_url(
          article[:url]
        )

      return if
        by_url.key?(url)

      articles <<
        article

      by_url[url] =
        article
    end

    # ========================================================================
    # RELATION FINDER
    # ========================================================================

    def self.find_relations(
      current,
      graph,
      settings,
      _config
    )

      relations = []

      minimum =
        settings[
          "minimum_relevance"
        ].to_i

      # ----------------------------------------------------------------------
      # ARTICLE
      # ----------------------------------------------------------------------

      if current[:type] == :article

        # --------------------------------------------------------------------
        # Article -> Product
        # --------------------------------------------------------------------

        graph[:products].each do |product|

          score =
            article_product_score(
              current,
              product
            )

          next if
            score < minimum

          opportunity =
            find_link_opportunity(
              current,
              product
            )

          next unless
            opportunity

          relations << {
            type: "article_to_product",
            source: current,
            target: product,
            score: score,
            opportunity: opportunity
          }

        end

        # --------------------------------------------------------------------
        # Article -> Article
        # --------------------------------------------------------------------

        graph[:articles].each do |article|

          next if
            normalize_url(article[:url]) ==
            normalize_url(current[:url])

          score =
            article_article_score(
              current,
              article
            )

          next if
            score < minimum

          opportunity =
            find_link_opportunity(
              current,
              article
            )

          next unless
            opportunity

          relations << {
            type: "article_to_article",
            source: current,
            target: article,
            score: score,
            opportunity: opportunity
          }

        end

      end

      # ----------------------------------------------------------------------
      # PRODUCT
      # ----------------------------------------------------------------------

      if current[:type] == :product

        # --------------------------------------------------------------------
        # Product -> Article
        # --------------------------------------------------------------------

        graph[:articles].each do |article|

          score =
            product_article_score(
              current,
              article,
              graph
            )

          next if
            score < minimum

          opportunity =
            find_article_link_opportunity(
              current,
              article,
              graph
            )

          next unless
            opportunity

          relations << {
            type: "product_to_article",
            source: current,
            target: article,
            score: score,
            opportunity: opportunity
          }

        end

        # --------------------------------------------------------------------
        # Product -> Product
        # --------------------------------------------------------------------

        graph[:products].each do |product|

          next if
            product[:id] == current[:id]

          score =
            product_product_score(
              current,
              product,
              graph
            )

          next if
            score < minimum

          opportunity =
            find_link_opportunity(
              current,
              product
            )

          next unless
            opportunity

          relations << {
            type: "product_to_product",
            source: current,
            target: product,
            score: score,
            opportunity: opportunity
          }

        end

      end

      # ----------------------------------------------------------------------
      # Classify relationships
      # ----------------------------------------------------------------------

      relations.each do |relation|

        relation[:anchor_quality] =
          anchor_quality(
            relation[:opportunity][:keyword],
            relation[:target]
          )

        relation[:reason] =
          relation_reason(
            relation
          )

        relation[:confidence] =
          confidence_level(
            relation[:score],
            relation[:anchor_quality],
            relation[:reason],
            settings
          )

        relation[:hardware_match] =
          if relation[:type] == "product_to_article" &&
             relation[:target][:required_hardware].include?(
               relation[:source][:id]
             )

            100

          else

            0

          end

      end

      # ----------------------------------------------------------------------
      # Confidence filter
      # ----------------------------------------------------------------------

      relations =
        relations.select do |relation|

          confidence_allowed?(
            relation[:confidence],
            settings["minimum_confidence"]
          )

        end

      # ----------------------------------------------------------------------
      # Ranking
      # ----------------------------------------------------------------------

      relations.sort_by! do |relation|

        [
          -confidence_weight(
            relation[:confidence]
          ),
          -relation[:hardware_match].to_i,
          -relation[:score],
          -relation[:anchor_quality],
          -relation[:opportunity][:keyword].to_s.length
        ]

      end

      relations
    end

    # ========================================================================
    # ARTICLE -> PRODUCT
    # ========================================================================

    def self.article_product_score(
      article,
      product
    )

      if article[:required_hardware].include?(
        product[:id]
      )

        return 100

      end

      return 0 unless
        product_keyword_match?(
          article,
          product
        )

      score =
        75

      score += [
        shared_values_score(
          article[:tags],
          product[:tags],
          2
        ),
        8
      ].min

      score += [
        shared_values_score(
          article[:categories],
          product[:categories],
          2
        ),
        5
      ].min

      score += [
        token_similarity(
          article[:tokens],
          product[:tokens]
        ),
        7
      ].min

      [
        score,
        100
      ].min
    end

    # ========================================================================
    # ARTICLE -> ARTICLE
    # ========================================================================

    def self.article_article_score(
      article_a,
      article_b
    )

      score =
        0

      shared_hardware =
        article_a[:required_hardware] &
        article_b[:required_hardware]

      score += [
        shared_hardware.length * 25,
        50
      ].min

      score += [
        shared_values_score(
          article_a[:tags],
          article_b[:tags],
          3
        ),
        12
      ].min

      score += [
        shared_values_score(
          article_a[:categories],
          article_b[:categories],
          3
        ),
        8
      ].min

      score += [
        token_similarity(
          article_a[:tokens],
          article_b[:tokens]
        ),
        15
      ].min

      [
        score,
        100
      ].min
    end

    # ========================================================================
    # PRODUCT -> ARTICLE
    # ========================================================================

    def self.product_article_score(
      product,
      article,
      graph
    )

      # ----------------------------------------------------------------------
      # Required hardware = definitive relationship
      # ----------------------------------------------------------------------

      if article[:required_hardware].include?(
        product[:id]
      )

        return 100

      end

      # ----------------------------------------------------------------------
      # Article explicitly mentions product
      # ----------------------------------------------------------------------

      unless product_mentioned_in_article?(
        product,
        article
      )

        return 0

      end

      score =
        75

      # ----------------------------------------------------------------------
      # Product/article index confirmation
      # ----------------------------------------------------------------------

      if graph[:product_articles][product[:id]].include?(
        article[:id]
      )

        score += 10

      end

      # ----------------------------------------------------------------------
      # Shared tags
      # ----------------------------------------------------------------------

      score += [
        shared_values_score(
          product[:tags],
          article[:tags],
          2
        ),
        5
      ].min

      # ----------------------------------------------------------------------
      # Shared categories
      # ----------------------------------------------------------------------

      score += [
        shared_values_score(
          product[:categories],
          article[:categories],
          2
        ),
        5
      ].min

      [
        score,
        100
      ].min
    end

    # ========================================================================
    # PRODUCT -> PRODUCT
    # ========================================================================

    def self.product_product_score(
      product_a,
      product_b,
      graph
    )

      explicit_related =
        product_a[:related].include?(
          product_b[:id]
        ) ||
        product_b[:related].include?(
          product_a[:id]
        )

      articles_a =
        graph[:product_articles][
          product_a[:id]
        ]

      articles_b =
        graph[:product_articles][
          product_b[:id]
        ]

      shared_articles =
        articles_a & articles_b

      return 0 unless
        explicit_related ||
        !shared_articles.empty?

      score =
        0

      score += 70 if
        product_a[:related].include?(
          product_b[:id]
        )

      score += 70 if
        product_b[:related].include?(
          product_a[:id]
        )

      unless shared_articles.empty?

        score += [
          shared_articles.length * 30,
          60
        ].min

      end

      [
        score,
        100
      ].min
    end

    # ========================================================================
    # PRODUCT KEYWORD MATCH
    # ========================================================================

    def self.product_keyword_match?(
      article,
      product
    )

      product[:keywords].any? do |keyword|

        value =
          normalize_text(
            keyword
          )

        next false unless
          usable_keyword?(
            value,
            explicit:
              explicit_product_keyword?(
                product,
                keyword
              )
          )

        article[:text].include?(
          value
        )

      end
    end

    def self.product_mentioned_in_article?(
      product,
      article
    )

      product_keyword_match?(
        article,
        product
      )
    end

    # ========================================================================
    # LINK OPPORTUNITY
    # ========================================================================

    def self.find_link_opportunity(
      source,
      target
    )

      return nil if
        existing_link?(
          source,
          target[:url]
        )

      keywords =
        target[:keywords].dup

      if target[:type] == :product

        keywords =
          preferred_product_keywords(
            target
          )

      elsif target[:type] == :article

        keywords =
          target[:keywords].dup

      end

      keywords =
        clean_anchor_candidates(
          keywords,
          target
        )

      keywords.each do |keyword|

        opportunity =
          find_keyword_occurrence(
            source[:content],
            keyword
          )

        return opportunity if
          opportunity

      end

      nil
    end

    # ========================================================================
    # PRODUCT -> ARTICLE LINK OPPORTUNITY
    # ========================================================================

    def self.find_article_link_opportunity(
      source,
      article,
      graph
    )

      return nil if
        existing_link?(
          source,
          article[:url]
        )

      keywords =
        article_link_keywords(
          article,
          graph
        )

      keywords =
        clean_anchor_candidates(
          keywords,
          article
        )

      keywords.each do |keyword|

        opportunity =
          find_keyword_occurrence(
            source[:content],
            keyword
          )

        return opportunity if
          opportunity

      end

      nil
    end

    # ========================================================================
    # ARTICLE LINK KEYWORDS
    # ========================================================================

    def self.article_link_keywords(
      article,
      graph
    )

      keywords = []

      # ----------------------------------------------------------------------
      # Explicit article keywords / title
      # ----------------------------------------------------------------------

      keywords.concat(
        article[:keywords]
      )

      # ----------------------------------------------------------------------
      # Required hardware
      #
      # This is the important V3.6 change.
      #
      # Example:
      #
      # Article:
      #   ILI9341 Display with ESP32
      #
      # required_hardware:
      #   - ili9341-xpt2046-2-8-touchscreen
      #
      # Product page contains:
      #   ILI9341
      #
      # The product can now naturally link to the article using:
      #
      #   ILI9341
      #
      # instead of requiring the complete article title to appear.
      # ----------------------------------------------------------------------

      article[:required_hardware].each do |product_id|

        product =
          graph[:by_product_id][product_id]

        next unless
          product

        keywords.concat(
          preferred_product_keywords(
            product
          )
        )

      end

      keywords
        .map do |keyword|

          keyword.to_s.strip

        end
        .reject(&:empty?)
        .uniq
        .sort_by do |keyword|

          -anchor_specificity(
            keyword
          )

        end
    end

    # ========================================================================
    # ANCHOR CANDIDATES
    # ========================================================================

    def self.preferred_product_keywords(
      product
    )

      title =
        product[:title].to_s.strip

      product_id =
        product[:id].to_s.strip

      explicit =
        product[:keywords].reject do |keyword|

          normalize_text(keyword) ==
            normalize_text(product_id) ||

          normalize_text(keyword) ==
            normalize_text(title)

        end

      # Explicit / derived keywords first.
      # Product title second.
      # Product ID last.
      explicit +
        [title, product_id]
    end

    # ========================================================================
    # CLEAN ANCHOR CANDIDATES
    # ========================================================================

    def self.clean_anchor_candidates(
      keywords,
      target
    )

      keywords
        .map do |keyword|

          keyword.to_s.strip

        end
        .reject(&:empty?)
        .uniq
        .select do |keyword|

          value =
            normalize_text(
              keyword
            )

          explicit =
            target[:type] == :product &&
            explicit_product_keyword?(
              target,
              keyword
            )

          usable_keyword?(
            value,
            explicit: explicit
          )

        end
        .sort_by do |keyword|

          explicit =
            target[:type] == :product &&
            explicit_product_keyword?(
              target,
              keyword
            )

          [
            explicit ? 0 : 1,
            -anchor_specificity(keyword),
            -keyword.length
          ]

        end
    end

    # ========================================================================
    # USABLE KEYWORD
    # ========================================================================

    def self.usable_keyword?(
      value,
      explicit: false
    )

      return false if
        value.empty?

      # Explicitly configured keywords are allowed.
      return true if
        explicit

      return false if
        GENERIC_ANCHORS.include?(value)

      words =
        value.split

      return false if
        words.length == 1 &&
        value.length < 4

      return false if
        words.length == 1 &&
        GENERIC_ANCHORS.include?(value)

      true
    end

    # ========================================================================
    # EXPLICIT PRODUCT KEYWORD
    # ========================================================================

    def self.explicit_product_keyword?(
      product,
      keyword
    )

      id =
        normalize_text(
          product[:id]
        )

      title =
        normalize_text(
          product[:title]
        )

      value =
        normalize_text(
          keyword
        )

      value != id &&
        value != title
    end

    # ========================================================================
    # FIND KEYWORD OCCURRENCE
    # ========================================================================

    def self.find_keyword_occurrence(
      content,
      keyword
    )

      return nil if
        content.to_s.empty?

      return nil if
        keyword.to_s.empty?

      protected_pattern =
        /<(#{PROTECTED_TAGS.join("|")})(?:\s[^>]*)?>.*?<\/\1>/im

      masked_content =
        content.gsub(
          protected_pattern
        ) do |match|

          " " * match.length

        end

      # Protect Markdown links/images.
      markdown_pattern =
        /!?\[[^\]]+\]\([^)]+\)/

      masked_content =
        masked_content.gsub(
          markdown_pattern
        ) do |match|

          " " * match.length

        end

      # Protect Markdown headings.
      markdown_heading_pattern =
        /^\s{0,3}\#{1,6}\s+.*$/

      masked_content =
        masked_content.gsub(
          markdown_heading_pattern
        ) do |match|

          " " * match.length

        end

      escaped =
        Regexp.escape(
          keyword
        )

      pattern =
        /(?<![\w\-])#{escaped}(?![\w\-])/i

      match =
        pattern.match(
          masked_content
        )

      return nil unless
        match

      {
        keyword: match[0],
        index: match.begin(0),
        length: match[0].length
      }
    end

    # ========================================================================
    # INSERT LINKS
    # ========================================================================

    def self.insert_links(
      current,
      relations,
      settings
    )

      content =
        current[:content].to_s

      return content if
        content.empty?

      total =
        0

      product_links =
        0

      article_links =
        0

      used_targets =
        []

      relations.each do |relation|

        break if
          total >=
          settings[
            "max_total_links_per_page"
          ].to_i

        target_url =
          normalize_url(
            relation[:target][:url]
          )

        next if
          used_targets.include?(
            target_url
          )

        if relation[:type].include?(
          "product"
        )

          next if
            product_links >=
            settings[
              "max_product_links_per_page"
            ].to_i

        else

          next if
            article_links >=
            settings[
              "max_article_links_per_page"
            ].to_i

        end

        source =
          current.merge(
            content: content
          )

        # Product -> Article uses the V3.6 hardware-aware
        # opportunity finder.
        opportunity =
          if relation[:type] == "product_to_article"

            find_article_link_opportunity(
              source,
              relation[:target],
              build_graph(
                current[:site]
              )
            )

          else

            find_link_opportunity(
              source,
              relation[:target]
            )

          end

        # The current node does not normally carry :site.
        # Therefore fall back to the opportunity already calculated
        # during relation discovery when necessary.
        opportunity ||=
          relation[:opportunity]

        next unless
          opportunity

        keyword =
          opportunity[:keyword]

        escaped_keyword =
          Regexp.escape(
            keyword
          )

        href =
          target_url.gsub(
            '"',
            "&quot;"
          )

        pattern =
          /(?<![\w\-\[>])#{escaped_keyword}(?![\w\-])/i

        replacement =
          %(<a href="#{href}" #{AUTO_LINK_ATTRIBUTE}>#{keyword}</a>)

        new_content =
          replace_first_safe_occurrence(
            content,
            pattern,
            replacement
          )

        next if
          new_content == content

        content =
          new_content

        used_targets <<
          target_url

        total +=
          1

        if relation[:type].include?(
          "product"
        )

          product_links +=
            1

        else

          article_links +=
            1

        end
      end

      content
    end

    # ========================================================================
    # SAFE REPLACEMENT
    # ========================================================================

    def self.replace_first_safe_occurrence(
      content,
      pattern,
      replacement
    )

      protected_parts =
        []

      protected_pattern =
        /<(#{PROTECTED_TAGS.join("|")})(?:\s[^>]*)?>.*?<\/\1>/im

      working =
        content.gsub(
          protected_pattern
        ) do |match|

          placeholder =
            "__EN_PROTECTED_#{protected_parts.length}__"

          protected_parts <<
            match

          placeholder
        end

      auto_parts =
        []

      working =
        working.gsub(
          AUTO_LINK_PATTERN
        ) do |match|

          placeholder =
            "__EN_AUTO_#{auto_parts.length}__"

          auto_parts <<
            match

          placeholder
        end

      markdown_parts =
        []

      working =
        working.gsub(
          /!?\[[^\]]+\]\([^)]+\)/
        ) do |match|

          placeholder =
            "__EN_MARKDOWN_#{markdown_parts.length}__"

          markdown_parts <<
            match

          placeholder
        end

      heading_parts =
        []

      working =
        working.gsub(
          /^\s{0,3}\#{1,6}\s+.*$/
        ) do |match|

          placeholder =
            "__EN_HEADING_#{heading_parts.length}__"

          heading_parts <<
            match

          placeholder
        end

      inline_parts =
        []

      working =
        working.gsub(
          /`[^`\n]+`/
        ) do |match|

          placeholder =
            "__EN_INLINE_#{inline_parts.length}__"

          inline_parts <<
            match

          placeholder
        end

      replaced =
        working.sub(
          pattern,
          replacement
        )

      return content if
        replaced == working

      markdown_parts.each_with_index do |original, index|

        replaced =
          replaced.gsub(
            "__EN_MARKDOWN_#{index}__",
            original
          )

      end

      heading_parts.each_with_index do |original, index|

        replaced =
          replaced.gsub(
            "__EN_HEADING_#{index}__",
            original
          )

      end

      inline_parts.each_with_index do |original, index|

        replaced =
          replaced.gsub(
            "__EN_INLINE_#{index}__",
            original
          )

      end

      auto_parts.each_with_index do |original, index|

        replaced =
          replaced.gsub(
            "__EN_AUTO_#{index}__",
            original
          )

      end

      protected_parts.each_with_index do |original, index|

        replaced =
          replaced.gsub(
            "__EN_PROTECTED_#{index}__",
            original
          )

      end

      replaced
    end

    # ========================================================================
    # GENERATED LINK CLEANUP
    # ========================================================================

    def self.remove_generated_links(
      content
    )

      content.to_s.gsub(
        AUTO_LINK_PATTERN
      ) do |match|

        inner =
          match.sub(
            /\A<a\b[^>]*>/i,
            ''
          )

        inner.sub(
          /<\/a>\z/i,
          ''
        )

      end
    end

    # ========================================================================
    # EXISTING LINK DETECTION
    # ========================================================================

    def self.existing_link?(
      source,
      target_url
    )

      content =
        source[:content].to_s

      return false if
        content.empty?

      normalized =
        normalize_url(
          target_url
        )

      escaped =
        Regexp.escape(
          normalized
        )

      return true if
        content.match?(
          /href\s*=\s*["']#{escaped}["']/i
        )

      return true if
        content.match?(
          /\]\(\s*#{escaped}(?:[#?][^)]*)?\s*\)/i
        )

      no_slash =
        normalized.chomp("/")

      return false if
        no_slash.empty?

      escaped_no_slash =
        Regexp.escape(
          no_slash
        )

      return true if
        content.match?(
          /href\s*=\s*["']#{escaped_no_slash}["']/i
        )

      return true if
        content.match?(
          /\]\(\s*#{escaped_no_slash}(?:[#?][^)]*)?\s*\)/i
        )

      false
    end

    # ========================================================================
    # ANCHOR QUALITY
    # ========================================================================

    def self.anchor_quality(
      keyword,
      target
    )

      value =
        normalize_text(
          keyword
        )

      return 0 if
        value.empty?

      title =
        normalize_text(
          target[:title]
        )

      return 100 if
        !title.empty? &&
        value == title

      if target[:type] == :product

        return 95 if
          explicit_product_keyword?(
            target,
            keyword
          )

      end

      return 90 if
        value.split.length >= 2

      return 85 if
        value.length >= 5

      70
    end

    # ========================================================================
    # ANCHOR SPECIFICITY
    # ========================================================================

    def self.anchor_specificity(
      keyword
    )

      value =
        normalize_text(
          keyword
        )

      return 0 if
        value.empty?

      score =
        0

      # Technical identifiers:
      # ILI9341
      # XPT2046
      # MPU6050
      score +=
        value.scan(
          /\b[a-z]{2,}\d{2,}[a-z0-9_-]*\b/i
        ).length * 20

      # Multi-word phrases.
      score +=
        value.split.length * 10

      # Longer phrases are usually more specific.
      score +=
        [
          value.length,
          30
        ].min

      score
    end

    # ========================================================================
    # RELATION REASON
    # ========================================================================

    def self.relation_reason(
      relation
    )

      source =
        relation[:source]

      target =
        relation[:target]

      type =
        relation[:type]

      case type

      when "article_to_product"

        return "required_hardware" if
          source[:required_hardware].include?(
            target[:id]
          )

        return "explicit_product_mention" if
          product_keyword_match?(
            source,
            target
          )

        "contextual_product_match"

      when "product_to_article"

        return "required_hardware" if
          target[:required_hardware].include?(
            source[:id]
          )

        return "explicit_product_mention" if
          product_mentioned_in_article?(
            source,
            target
          )

        "contextual_article_match"

      when "product_to_product"

        return "explicit_related" if
          source[:related].include?(
            target[:id]
          ) ||
          target[:related].include?(
            source[:id]
          )

        "shared_article"

      when "article_to_article"

        shared =
          source[:required_hardware] &
          target[:required_hardware]

        return "shared_hardware" unless
          shared.empty?

        "contextual_article_match"

      else

        "contextual_match"

      end
    end

    # ========================================================================
    # CONFIDENCE
    # ========================================================================

    def self.confidence_level(
      score,
      anchor_quality,
      reason,
      settings
    )

      high_score =
        settings[
          "high_confidence_score"
        ].to_i

      medium_score =
        settings[
          "medium_confidence_score"
        ].to_i

      return "high" if
        reason == "required_hardware"

      return "high" if
        reason == "explicit_related" &&
        score >= medium_score

      return "high" if
        reason == "shared_hardware" &&
        score >= medium_score

      return "high" if
        reason == "explicit_product_mention" &&
        score >= high_score

      return "high" if
        score >= high_score &&
        anchor_quality >= 95

      return "medium" if
        score >= medium_score &&
        anchor_quality >= 85

      "low"
    end

    # ========================================================================
    # CONFIDENCE FILTER
    # ========================================================================

    def self.confidence_allowed?(
      confidence,
      minimum
    )

      order = {
        "low" => 1,
        "medium" => 2,
        "high" => 3
      }

      actual =
        order[
          confidence.to_s.downcase
        ] || 1

      required =
        order[
          minimum.to_s.downcase
        ] || 2

      actual >=
        required
    end

    # ========================================================================
    # CONFIDENCE WEIGHT
    # ========================================================================

    def self.confidence_weight(
      confidence
    )

      case confidence.to_s.downcase

      when "high"
        3

      when "medium"
        2

      else
        1

      end
    end

    # ========================================================================
    # PRODUCT OVERRIDES
    # ========================================================================

    def self.product_override(
      config,
      product_id
    )

      overrides =
        config["overrides"]

      return {} unless
        overrides.is_a?(Hash)

      id =
        product_id.to_s.strip

      return {} if
        id.empty?

      override =
        overrides[id]

      override.is_a?(Hash) ?
        override :
        {}
    end

    # ========================================================================
    # PRODUCT KEYWORDS
    # ========================================================================

    def self.product_keywords(
      data,
      override = {}
    )

      keywords =
        []

      product_id =
        data["product_id"].to_s.strip

      title =
        data["title"].to_s.strip

      # ----------------------------------------------------------------------
      # Override keywords - highest priority
      # ----------------------------------------------------------------------

      if override.is_a?(Hash)

        Array(
          override["keywords"]
        ).each do |keyword|

          value =
            keyword.to_s.strip

          keywords <<
            value unless
            value.empty?

        end
      end

      # ----------------------------------------------------------------------
      # Explicit front matter keywords
      # ----------------------------------------------------------------------

      Array(
        data["internal_link_keywords"]
      ).each do |keyword|

        value =
          keyword.to_s.strip

        keywords <<
          value unless
          value.empty?

      end

      # ----------------------------------------------------------------------
      # Automatically derived keywords
      # ----------------------------------------------------------------------

      keywords.concat(
        derived_product_keywords(
          title
        )
      )

      # ----------------------------------------------------------------------
      # Product title
      # ----------------------------------------------------------------------

      keywords <<
        title unless
        title.empty?

      # ----------------------------------------------------------------------
      # Product ID - final fallback
      # ----------------------------------------------------------------------

      keywords <<
        product_id unless
        product_id.empty?

      keywords
        .map(&:strip)
        .reject(&:empty?)
        .uniq
        .sort_by do |keyword|

          -anchor_specificity(
            keyword
          )

        end
    end

    # ========================================================================
    # DERIVED PRODUCT KEYWORDS
    # ========================================================================

    def self.derived_product_keywords(
      title
    )

      value =
        title.to_s.strip

      return [] if
        value.empty?

      normalized =
        normalize_text(
          value
        )

      candidates =
        []

      words =
        normalized.split

      # ----------------------------------------------------------------------
      # Technical identifiers
      # ----------------------------------------------------------------------

      identifiers =
        normalized
          .scan(
            /\b[a-z]{2,}\d{2,}[a-z0-9_-]*\b/i
          )
          .uniq

      candidates.concat(
        identifiers
      )

      # ----------------------------------------------------------------------
      # Identifier combinations
      # ----------------------------------------------------------------------

      if identifiers.length >= 2

        candidates <<
          identifiers.join(" ")

      end

      # ----------------------------------------------------------------------
      # Relevant technical terms
      # ----------------------------------------------------------------------

      relevant_terms =
        words.select do |word|

          %w[
            touchscreen
            touch
            display
            lcd
            tft
            sensor
            module
            controller
            board
            breakout
          ].include?(word)

        end

      # ----------------------------------------------------------------------
      # Identifier + technical term
      # ----------------------------------------------------------------------

      identifiers.each do |identifier|

        relevant_terms.each do |term|

          candidates <<
            "#{identifier} #{term}"

        end

      end

      # ----------------------------------------------------------------------
      # Display size + technical term
      # ----------------------------------------------------------------------

      size_match =
        value.match(
          /(\d+(?:\.\d+)?)\s*["']?\s*(?:inch|in)?/i
        )

      if size_match &&
         relevant_terms.include?(
           "touchscreen"
         )

        candidates <<
          "#{size_match[1]} inch touchscreen"

      end

      candidates
    end

    # ========================================================================
    # ARTICLE KEYWORDS
    # ========================================================================

    def self.article_keywords(
      data
    )

      keywords =
        []

      title =
        data["title"].to_s.strip

      keywords <<
        title unless
        title.empty?

      Array(
        data["internal_link_keywords"]
      ).each do |keyword|

        value =
          keyword.to_s.strip

        keywords <<
          value unless
          value.empty?

      end

      keywords
        .uniq
        .sort_by do |keyword|

          -keyword.length

        end
    end

    # ========================================================================
    # REQUIRED HARDWARE
    # ========================================================================

    def self.extract_hardware_ids(
      value
    )

      return [] unless
        value.is_a?(Array)

      value.map do |item|

        if item.is_a?(Hash)

          item["id"].to_s.strip

        else

          item.to_s.strip

        end

      end
      .reject(&:empty?)
      .uniq
    end

    # ========================================================================
    # EXCLUDED EDITORIAL PAGES
    # ========================================================================

    def self.excluded_editorial_page?(
      document
    )

      url =
        normalize_url(
          document.url
        ).downcase

      excluded_paths = [
        "/tutorials/",
        "/products/",
        "/categories/",
        "/tags/",
        "/recommended-hardware/",
        "/search/",
        "/archive/"
      ]

      excluded_paths.any? do |path|

        url == path ||
          url.start_with?(
            path + "/"
          )

      end
    end

    # ========================================================================
    # EDITORIAL COLLECTION
    # ========================================================================

    def self.editorial_collection_document?(
      document
    )

      data =
        document.data || {}

      return true if
        data["internal_links"] == true

      EDITORIAL_LAYOUTS.include?(
        data["layout"].to_s
      )
    end

    # ========================================================================
    # SCORING HELPERS
    # ========================================================================

    def self.shared_values_score(
      a,
      b,
      points
    )

      (a & b).length *
        points
    end

    def self.token_similarity(
      tokens_a,
      tokens_b
    )

      return 0 if
        tokens_a.empty? ||
        tokens_b.empty?

      shared =
        tokens_a &
        tokens_b

      return 0 if
        shared.empty?

      [
        shared.length * 2,
        20
      ].min
    end

    # ========================================================================
    # TOKENIZER
    # ========================================================================

    def self.tokenize(
      text
    )

      stopwords = %w[
        the
        and
        or
        for
        with
        this
        that
        from
        into
        using
        use
        used
        are
        is
        to
        of
        a
        an
        in
        on
        our
        your
        how
        what
        can
        will
        be
        tutorial
        guide
        project
        projects
        display
        code
        example
        learn
        common
        popular
        embedded
        electronics
        device
        devices
      ]

      normalize_text(
        text
      )
        .scan(
          /[a-z0-9][a-z0-9_-]{2,}/
        )
        .reject do |word|

          stopwords.include?(
            word
          )

        end
        .uniq
    end

    # ========================================================================
    # NORMALIZATION
    # ========================================================================

    def self.normalize_text(
      value
    )

      value.to_s
        .downcase
        .gsub(
          /[^a-z0-9_\-\s]/,
          " "
        )
        .gsub(
          /\s+/,
          " "
        )
        .strip
    end

    def self.normalize_array(
      value
    )

      Array(value)
        .map do |item|

          normalize_text(
            item
          )

        end
        .reject(&:empty?)
        .uniq
    end

    def self.normalize_ids(
      value
    )

      Array(value)
        .map do |item|

          if item.is_a?(Hash)

            item["id"].to_s.strip

          else

            item.to_s.strip

          end

        end
        .reject(&:empty?)
        .uniq
    end

    def self.normalize_url(
      url
    )

      value =
        url.to_s.strip

      value =
        value.split("#").first

      value =
        value.split("?").first

      value =
        "/" if
        value.empty?

      value =
        "/#{value}" unless
        value.start_with?("/")

      value =
        value.chomp("/")

      return "/" if
        value.empty?

      "#{value}/"
    end

    # ========================================================================
    # COUNT GENERATED LINKS
    # ========================================================================

    def self.count_generated_links(
      content
    )

      content.to_s.scan(
        AUTO_LINK_PATTERN
      ).length
    end

    # ========================================================================
    # ANALYSIS LOG
    # ========================================================================

    def self.log_analysis(
      current,
      relations,
      settings
    )

      limit =
        settings[
          "analysis_results_per_page"
        ].to_i

      limit =
        5 if
        limit <= 0

      Jekyll.logger.info(
        "Embedded Nerd:",
        "============================================================"
      )

      Jekyll.logger.info(
        "Embedded Nerd:",
        "Internal Link Analysis V3.6"
      )

      Jekyll.logger.info(
        "Embedded Nerd:",
        "#{current[:type].to_s.upcase}: #{current[:title]}"
      )

      Jekyll.logger.info(
        "Embedded Nerd:",
        "URL: #{current[:url]}"
      )

      if relations.empty?

        Jekyll.logger.info(
          "Embedded Nerd:",
          "No linkable relationships found."
        )

      else

        relations.first(limit).each do |relation|

          anchor =
            relation[:opportunity][:keyword]

          Jekyll.logger.info(
            "Embedded Nerd:",
            "#{relation[:type]} | " \
            "#{relation[:target][:title]} | " \
            "score=#{relation[:score]} | " \
            "anchor=\"#{anchor}\" | " \
            "anchor_quality=#{relation[:anchor_quality]} | " \
            "confidence=#{relation[:confidence].upcase} | " \
            "reason=#{relation[:reason]} | " \
            "#{relation[:target][:url]}"
          )

        end
      end

      Jekyll.logger.info(
        "Embedded Nerd:",
        "============================================================"
      )
    end
  end
end

# ============================================================================
# JEKYLL HOOKS
# ============================================================================

Jekyll::Hooks.register :posts, :pre_render do |post|

  EmbeddedNerd::InternalLinker.process(
    post
  )

end

Jekyll::Hooks.register :pages, :pre_render do |page|

  EmbeddedNerd::InternalLinker.process(
    page
  )

end

Jekyll::Hooks.register :documents, :pre_render do |document|

  data =
    document.data || {}

  # Posts are already handled by :posts.
  if document.respond_to?(:collection) &&
     document.collection &&
     document.collection.label.to_s == "posts"

    next

  end

  if data["layout"].to_s == "product"

    EmbeddedNerd::InternalLinker.process(
      document
    )

  elsif data["internal_links"] == true

    EmbeddedNerd::InternalLinker.process(
      document
    )

  elsif EmbeddedNerd::InternalLinker::EDITORIAL_LAYOUTS.include?(
    data["layout"].to_s
  )

    EmbeddedNerd::InternalLinker.process(
      document
    )

  end
end
